### ISSUE TITLE
feat: create modal component

### ISSUE THREAD

**Issue by f1rstf1y9** [f1rstf1y9/weirdsector-board#11]
## Description

> Modal 컴포넌트를 생성하여 반응형 헤더의 대시보드 클릭 시, 수정 및 삭제 시에 적용하기

## TODO

- [x] Modal 컴포넌트 생성
- [x] 대시보드 클릭시 모달창 띄우기
- [x] 게시글 수정, 삭제 시 모달창 띄우기
