### ISSUE TITLE
design: mobile screen layout

### ISSUE THREAD

**Issue by f1rstf1y9** [f1rstf1y9/weirdsector-board#21]
## Description

> 뷰포트 너비 640px 이하에서 레이아웃 깨짐

## TODO

- [x] 게시글의 댓글 작성 부분
- [x] 게시글 작성 페이지
- [x] 게시글 수정 페이지
