### ISSUE TITLE
refactor: change class to className

### ISSUE THREAD

**Issue by f1rstf1y9** [f1rstf1y9/weirdsector-board#6]
## Description

> className으로 작성되어야 할 부분이 class로 작성됨.

## TODO

- [x] Layout.jsx 파일 수정
- [x] Header.jsx 파일 수정
- [x] Footer.jsx 파일 수정
- [x] LoginButton.jsx 파일 수정
