### ISSUE TITLE
refactor: covert the attributes of svg from kebab case to camel case

### ISSUE THREAD

**Issue by f1rstf1y9** [f1rstf1y9/weirdsector-board#7]
## Description

> svg요소의 attribute에 작성된 kebab-case를 camelCase로 변경

## TODO

- [x] .svg 파일 수정
- [x] BoardPagination.jsx 파일 수정
- [x] CheckBox.jsx 파일 수정
